# Generated by Django 3.1.4 on 2021-01-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaining', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='person',
            name='etat',
            field=models.CharField(choices=[('INT', 'Interne'), ('EXT', 'Externe')], default='EXT', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='statue',
            field=models.CharField(choices=[('DOC', 'doctorat'), ('MAS', 'master')], default='DOC', max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, upload_to='../media/images'),
        ),
    ]
