# Generated by Django 3.1.4 on 2021-01-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaining', '0002_auto_20210102_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sexe',
            field=models.CharField(choices=[('MAS', 'Masculin'), ('FEM', 'Feminin')], default='', max_length=10),
        ),
    ]
