# Generated by Django 3.1.4 on 2021-01-24 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaining', '0005_auto_20210124_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deplacement',
            name='date_depart',
            field=models.DateField(default=datetime.datetime(2021, 1, 24, 3, 40, 46, 976108)),
        ),
        migrations.AlterField(
            model_name='deplacement',
            name='date_retour',
            field=models.DateField(default=datetime.datetime(2021, 1, 25, 3, 40, 46, 976108)),
        ),
    ]
