# Generated by Django 3.1.4 on 2021-01-24 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaining', '0006_auto_20210124_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='deplacement',
            name='depenseEstimé',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AddField(
            model_name='deplacement',
            name='description',
            field=models.TextField(default='description', max_length=500),
        ),
        migrations.AddField(
            model_name='deplacement',
            name='evenement',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='deplacement',
            name='date_depart',
            field=models.DateField(default=datetime.datetime(2021, 1, 24, 4, 15, 48, 682608)),
        ),
        migrations.AlterField(
            model_name='deplacement',
            name='date_retour',
            field=models.DateField(default=datetime.datetime(2021, 1, 25, 4, 15, 48, 682608)),
        ),
    ]
